apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  protocol: kfserving  # Activate v2 protocol
  name: wines
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://models/rf-regressor  # note: s3 points to minio-seldon in the local kind cluster
        envSecretRefName: seldon-rclone-secret
        name: classifier
      name: default
      replicas: 1